title: Doha KHTATBA # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science and Machine Learning Research student with a solid background in Cloud and High Performance Computing, aspiring to break into the industry as a fresh graduate!
  <br><br>
  Currently an intern at Astek Group - working on improving the performance of ASR systems.
  <br><br>
  <a href="https://www.linkedin.com/in/doha-khtatba/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-4NK4REQ1JG # your Google Analytics tracking ID here
